internal/ui/common/styles.go
Currently jjui seems to use hardcoded True Color.
This changes to use hardcoded ANSI 16 colors, like jj itself. This allows for respecting the user's color scheme, including light mode support. This doesn't match `jj` default colors, but should keep the existing jjui colors for you.
=> feat: use base16 colors

internal/ui/revisions/keymap.go
This PR adds the missing keymap short help for the abandon operation. The remaining operations should already be present in the short help row.
=> fix: Add missing abandon keymap help to short help row

README.md, cmd/jjui/main.go, go.mod, internal/ui/abandon/abandon.go, internal/ui/bookmark/bookmarks.go, internal/ui/bookmark/set.go, internal/ui/bookmark/set_test.go, internal/ui/common/commands.go, internal/ui/common/msgs.go, internal/ui/confirmation/confirmation.go, internal/ui/describe/describe.go, internal/ui/describe/describe_test.go, internal/ui/diff/diff.go, internal/ui/revisions/details/details.go, internal/ui/revisions/details/details_test.go, internal/ui/revisions/renderer.go, internal/ui/revisions/revisions.go, internal/ui/revisions/revset/revset.go, internal/ui/revisions/revset/revset_test.go, internal/ui/status/status.go, internal/ui/ui.go, test/parse_test.go, test/shell.go, test/test_commands.go
I would like to install JJUI via `go install` (and, actually via [mise's Go backend](https://mise.jdx.dev/dev-tools/backends/go.html)https://[mise.jdx.dev/dev-tools/backends/go.html](https://mise.jdx.dev/dev-tools/backends/go.html)) but I cant because the module is named just `jjui` rather than `github.com/idursun/jjui`
This PR should allow for installing via either.
=> rename modules to allow remote go install

cmd/jjui/main.go
Since almost everyone is using colocated jj, I think it makes sense to use the git root as the default location. 
I use jjui in a tmux popover which uses the current working directory, so I'm only rarely in the git root directory when I run it.
Feel free to close if unwanted or request changes.
=> feat: use git root as location

README.md, flake.lock, flake.nix, nix/default.nix, nix/vendor-hash
jjui is already on nixpkgs. However as jjui evolves, it might be possible that people might want to try a fresh release without having to wait on it being available on nixpkgs. We now provide a simple flake for just that.
jjui can be run directly with:
```shell
nix run github:idursun/jjui
```
or added as an input on their flakes.
We also provide a minimal development shell for those wanting to contribute back to jjui.
=> Adding nix flake.

.github/workflows/nix.yml
Just to make sure that jjui is buildable with nix.
Previously, if we added a new Go dependency, we
wont notice the vendored-hash mismatch, since CI was not testing with nix.
Now we make sure that the package builds correctly under nix.
=> chore(nix): Add flake check GH action.

cmd/jjui/main.go
When building from a standalone VCS-free tarball of the repo, info.Main.Version is `(devel)`, not `""`.
This fix first check if main.Version has been set by the build options, then default to get the version info embedded by go.
This is necessary for  #72.
=> fix: allow build version to be set from ldflags

README.md
This PR updates the README to include installation instruction for archlinux-based distros.
Thank you for the great work of `jjui`. I just created an AUR package for `jjui` so that archlinux-based distro users can easily install it as well: https://aur.archlinux.org/packages/jjui-bin. I will maintain this package as long as needed.
=> Update instruction on installation for archlinux-based linux distros

internal/jj/bookmark_parser.go, internal/jj/bookmark_parser_test.go, internal/jj/commands.go, internal/ui/bookmarks/bookmarks.go, internal/ui/git/git.go, internal/ui/git/git_test.go
This PR adds `--allow-new` option to new local bookmarks. Previously this was not supported.
=> Automatically add `--allow-new` argument to new local bookmarks

internal/ui/revisions/revisions.go
Sets context'd selected item after a refresh. Code that set the selected item on context only exercised after the first user interaction which caused custom commands to fail due to not replacing the place holders.
fixes #99
=> fix(revisions): set selected item on refresh

internal/jj/commands.go, internal/ui/operations/details/details.go
I noticed that when working with repos with large files, there are some glitches and unneeded visual noise in jjui, e.g., when
viewing the details list:
viewing a diff:
viewing an operation:
This PR fixes these by avoiding snapshotting the working directory for the associated commands.
Even without snapshotting the working copy, viewing the details list still updates without the need for manually refreshing.
There are no tests..!
=> fix: snapshot working copy less often

internal/ui/git/git.go
Adds an explicit `--remote` argument to the git push commands of bookmarks with one or more remotes.
fixes #94
=> fix: add `--remote` argument to bookmarks with multiple remotes

.gitignore, README.md
After this, `go build ./...` will not result in `jj` trying to snapshot a binary file.
------
I have found it hard to get used to golang CLI idioms, so I'd have found these instructions useful.
If there's a better way, please let me know!
I'm guessing you're using Nix yourself, but it doesn't seem worth recommending it to people here unless they already know they want to use it.
=> Add compilation instructions and add `/jjui` to `.gitignore`

README.md
When I run `go build ./...`, something happens and no error is generated, but the binary does *not* get updated. `go build ./cmd/jjui` actually works.
=> Fixup build command from ebfae407b1

nix/default.nix
before:
```
➜ jjui --version     
(devel)
```
after
```
result/bin/jjui --version
0b5d3eb8e800989ed91845e131e49b8f3bacd21a
```
even better would be if I could retreive the next version to print `jjui 0.9-nightly+REV` or even the current version.
=> build(nix): add git version to --version

README.md
This PR removes one of the duplicated maintainer mentions, leaving the mention in the section title to correspond to other maintainer mentions.
=> doc: Remove a duplicated maintainer mention

cmd/jjui/main.go, internal/config/config.go
I think `--period` is better than `--interval`, because `-i` sounds more like "interactive". 
Fixes #148
-----
We could still go with `--interval`, or something else if we can come up with something better.
=> feat: add --period/-p CLI option

internal/config/keys.go, internal/jj/commands.go, internal/ui/common/msgs.go, internal/ui/context/custom_run_command.go, internal/ui/context/main_context.go, internal/ui/exec_process/exec_process.go, internal/ui/helppage/help.go, internal/ui/status/status.go, internal/ui/ui.go
This feature is inspired by Vim's `:` key and uses the footer line-editor to obtain input just like we have for `/` (search).
For example, using `: restore -i` will run `jj restore -i` command in interactive mode. jj will use the terminal to show its TUI.
We use the same facilities that allow CustomCommands to replace pleaceholders like `$file`, `$change_id`, `$operation_id`.
If the user specifies any of these as arguments to their commands they will be replaced with the context value.
We have two different exec keys: `:`, `$`.
- `:` 
As described above, allows running jj interactive commands. These commands can make use of the terminal for TUIs.
Examples: `: help`, `: squash -i`, etc.
- `$`
Run interactive shell commands via `$SHELL -c "<input>"`.
Examples: `$ man jj`, `$ jq . $file | …
=> feat(exec): Exec key `:` one-shot interactive jj commands.

internal/jj/commands.go, internal/ui/exec_process/exec_process.go
Instead of replacing context values on the command line string it is much better to expose them as environment variables for the process being run. This way if people use their own scripts they can access the contextual values as exposed on the env.
=> fix(exec_shell): Dont replace context values but set env.

internal/ui/context/leader.go, internal/ui/leader/leader.go, internal/ui/leader/leader_test.go, internal/ui/ui.go
This change allow Leader entries to also have an optional `context` (`[]string`) attribute. When present, it specifies the required context keys that MUST be available for the key to be shown.
This is useful for example for keys or submenus that must be shown only under certain contextual conditions.
The following example restricts the `e` key to be available ONLY when both `$file` and `$change_id` are available in context. That is, when the cursor is on change details over a file.
```toml
[leader.e]
context = [ "$file", "$change_id" ]
help = "Edit current file"
send = [ "$", "jj edit $change_id && $EDITOR $file", "enter" ]
```
=> feat(leader): Allow leader entries to specify context requirements.

internal/ui/revisions/revisions.go
This change fixes the `J` move to parent when change_id is not lowercase. 
Having the following graph, and starting the top, moving with `J` repeatedly should work like this:
`W`, `78` (change_id), `K`, `M`, `N`, `YPQP` ...
```
○  W vborja@apache.org 1 minute ago C
│  (no description set)
│ ○  R?? vborja@apache.org 1 minute ago A
├─╯  CONFIG_HOME
○  P?? vborja@apache.org 1 minute ago 78
│  (empty) (no description set)
│ ○  R?? vborja@apache.org 1 minute ago E9
│ │  CONFIG_HOME
│ ○  P?? vborja@apache.org 1 minute ago E6
├─╯  (no description set)
○  K vborja@apache.org 1 minute ago context* 5
│  feat(leader): Allow leader entries to specify context requirements.
@  M vborja@apache.org 1 minute ago 77
│  (no description set)
◆  N ibrahim@dursun.cc 21 hours ago main@idursun git_head() 2
│ …
```
=> fix(revisions): Using `J` should work on uppercase templated change_id

cmd/jjui/main.go
The current setup led to a confusing situation when I tried to debug `jjui` and told the debugger to use a different working dir when launching `jjui`. It did so, but since the debugger did not *also* change the PWD variable, `jjui` still used the directory I started the debugger from.
I am not sure whether it is a bug that the `dlv` debugger does not update PWD when run with the `-wd some_dir` argument. However, this commit does make `dlv debug ./cmd/jjui/  --headless --output /tmp/jjui-debug  -l 127.0.0.1:5566 --wd ~/dev/jj` work as expected. (If you try this command, note that the only way to quit it is `kill` or connecting to that port with a debugger client like VS Code, ^C does not work).
This might have some downsides I am unaware of. If using Getwd does not work for some reason, …
=> Use os.Getwd for getting the current dir

internal/jj/commands.go, internal/ui/context/command_runner.go, internal/ui/flash/flash.go, internal/ui/status/status.go, internal/ui/ui.go
Previously, revset errors were displayed under the revset component and similarly command errors were displayed under the status line. This not only looks out of place but also complicates the widget implementations unnecessarily. 
I have introduced a flash message view, which displays success and error messages at the bottom right corner. Success messages expire after 4 seconds, but error messages are sticky and they are dismissed by pressing `esc`.
Multiple messages stack on top of each other.
=> feat: add command outputs as (auto-expiring) flash messages

internal/config/loader.go
This is useful for jjui developers or other environments that for some reason do not follow conventions.
I (@vic) manage my dot files via nix. When applied, my dot files are immutable, but I still want to experiment with custom settings during jjui development. This change allows me to have jjui to load from a custom directory and not my stable home settings.
=> feat(loader): Support JJUI_CONFIG_DIR environment var.

.github/workflows/gh-pages.yml
This change renders our wiki documentation using [mdbook](https://github.com/rust-lang/mdBook) and publishes to github pages.
[Example published pages (from vic's jjui wiki fork)](https://vic.github.io/jjui/)
The advantage of having our wiki published as gh-pages are:
- People might want to see a beautiful documentation website.
- Our documentation website can be indexed by search engines.
- Generated website has integrated search, syntax lighlight.
- Wiki remains truth of source for documentation.
- Editing docs in wiki is easier and encourages contribution.
- Our website has a `print` button at the top-right, allowing people to save current documentation for offline usage (includes screenshots). see #166
> [!IMPORTANT]
>  Before merging, go to repository `Settings` / `Pages`.  Set …
=> feat(docs): Deploy to gh-pages.

internal/jj/commands.go
Use `--ignore-working-copy` on non-mutable commands to prevent creating snapshots when we only want to obtain data from jj store.
=> fix(commands): don't create snapshots when only querying current state.

internal/config/default/config.toml, internal/config/keys.go, internal/ui/ace_jump/ace_jump.go, internal/ui/graph/default_row_iterator.go, internal/ui/helppage/help.go, internal/ui/revisions/ace_jump.go, internal/ui/revisions/revisions.go, internal/ui/ui.go
This feature implements a simple vim like ace-jump to quickly move to revisions (`revisions.rows`) from the current revset.
Pressing `f` will highlight the first character of each change_id (only non-hidden, non-conflicting, and non-root) or each commit_id.
Wile ace-jump is enabled a temporary case-insensitive keymap is created that matches the next available keys from revisions ids. When an unambiguous revision is selected via its shortest id, the cursor is moved to that revision row.
This allows to have much faster movements than currently using `/` search and `'`
And also opens the door for a future PR to explore on making `/` work with fuzzy search (to match on full-description and not only on the content of the log being displayed) while preserving fast movements on revisions with …
=> feat(revisions): Ace jump to revision. `f` key on revisions view.

internal/ui/ui.go
This fixes two bugs:
- The preview resize messages were being handled even if the preview window was hidden. This caused strange problems if ctrl+h or ctrl+l were hit while preview was hidden.
We now only handle resize messages if preview is actually shown. Because these commands effects are intended to be immediatly visible to the user.
- There was no limit to scaling up and when we hit more than 100% the screen was messed up and preview window was no longer able to be resized.
=> fix(preview): Limit preview resize to range 5% up to 95%.

internal/ui/revisions/revisions.go
Automatically moves the cursor to the revision parent (on same branch) when a revision selection is toggled.
This is a QOL improvement when working on multiple revisions as you no longer have to move and only press space.
Implements the proposal from [#221 comment](https://github.com/idursun/jjui/discussions/221#discussioncomment-13898398) and makes moving-on-selection consistent on both revisions and files.
=> feat(revisions): Move to revision parent when toggle selection.

internal/ui/graph/renderer.go, internal/ui/revisions/ace_jump.go
Reducing the number of jump candidates to only those visible on screen improves the experience since you will likely jump faster as there are less revisions with the same prefix. It also avoids long-jumping to off-screen revisions since that felt weird. 
Thanks to the insight at https://github.com/idursun/jjui/pull/226#issuecomment-3128000055
=> fix(ace_jump): Allow jump only to revisions visible on screen

internal/config/config.go, internal/config/default/config.toml, internal/config/keys.go, internal/ui/ui.go
The option `preview.show_at_bottom` (default: false) and the `P` key
allow moving the preview window to the bottom instead of being shown to
the side.
Fixes #93
=> feat(preview): Allow showing preview at bottom (config and toggle-key)

internal/ui/fuzzy_input/fuzzy_input.go
Previous to this change if you entered `: somethi` that has no match in history and then you used `tab`, it expanded to empty string leaving your prompt as `:` which is quite annoying.
Now tab only accepts completion if there is actually any match shown.
=> fix(jj_exec): Tab key must only accept-suggestion if there are matches.

cmd/jjui/main.go, internal/config/config.go, internal/config/default/config.toml, internal/jj/commands.go
One of the few times something that _sounded_ easy _was_ easy.
Not certain if `preview` is the right table to add the `log_command` field, but happy to move it if there's a better place for it.
Tested that it works with both 2-line and 1-line log formats. (My preferred is a 1-line, hence this PR.)
Resolves #217
=> feat: make log format and revset configurable

internal/ui/confirmation/confirmation.go, internal/ui/confirmation/confirmation_test.go, internal/ui/operations/abandon/abandon.go, internal/ui/operations/details/details.go, internal/ui/operations/details/details_test.go, internal/ui/operations/details/show_details_operation.go, internal/ui/ui.go, internal/ui/undo/undo.go, test/shell.go
This helps the user to not having to move using direction keys, but directly use shortcuts instead.
Buttons are moved to their own line since now they occupy more space due to them including key-bindings help.
=> feat(confirmation): Show key-bindings on confirmation dialog.

internal/ui/fuzzy_input/fuzzy_input.go, internal/ui/status/status.go
This patch makes the following changes to the input for `jj exec`/`sh exec`: 
- When entering exec mode, fuzzy suggestions are OFF. This is more intuitive as you would expect on entering a system shell's prompt. Where you can use `ctrl+p`, `ctrl+n` to move on immediate history instead of moving on suggestions. 
- Suggestions are enabled with `ctrl+r`, again a common idiom on shells. First suggestion mode is fuzzy since it will most likely give the expected result.
- Using `ctrl+r` again switches to regex match, this is useful when trying to match more continuous strings than the fuzzy match algorithm.
- Using `ctrl+r` starts the cycle again by turning suggestions off.
Curently `ctrl+r` is not expected to be a customized keybinding (just like we can't directly customize the textinput …
=> feat(fuzzy_input): More intuitive movement on history and different suggestions modes.

internal/config/default/config.toml, internal/config/keys.go, internal/jj/commands.go, internal/ui/common/msgs.go, internal/ui/helppage/help.go, internal/ui/operations/details/details.go, internal/ui/operations/details/show_details_operation.go, internal/ui/revisions/revisions.go
This might not be worth adding, since the existing squash command is more general — so you may take it as a suggestion.
I often want to squash file(s) from the current revision into the parent. When using JJUI, I usually enter the details view first to see what's going on, then I select the files I want to squash. However, there is no squash operation in details mode: you must exit details, select the source revision, press `S`, select the parent, then interactively select the files.
This PR adds a shortcut `S` to the details view that squashes the selected files into the parent directly.
Limitations:
- You can only select at the level of files, not lines
- Squashing is always into the parent (if the parent is unique)
Despite its narrow scope, I use this command all the time, so perhaps …
=> feat: squash files from details view

internal/jj/commands.go, internal/ui/revisions/revisions.go
`jj describe` takes multiple revsets to describe. This change allows users to describe multiple revisions simultaneously by first selecting them via `space`, followed by `D`.
=> feat(describe): Allow multiple revisions

internal/config/default/config.toml, internal/config/keys.go, internal/ui/operations/describe/describe.go
Adds an "edit in editor" binding that lets you bail out from the inline describe editor to a full fledged editor.
Inspired by similar functionality that I missed from LazyGit
https://github.com/user-attachments/assets/7b994fb0-b41c-48aa-81c7-7a36623cedb5
=> feat: edit in editor escape hatch for inline describe editor

internal/ui/git/git.go, internal/ui/git/git_test.go, internal/ui/ui.go
This change allows the user to act on multiple selected revisions in the 'git operations' UI.
If only a single revision is selected, everything works as before. If multiple revisions are selected, there will be a single entry to push all selected in a single  `jj git push --change a --change b ...`  call.
In case of multiple revisions, the `c` shortcut will be bound to the new 'push all selected changes' entry and the entries to push a single change will have no keyboard shortcut bound to them.
=> feat(git): Support multiple revisions
